name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        id: checkout

      - name: Get Version
        id: get_version
        run: |
          echo "${GITHUB_REF}" | sed -E 's%^refs/tags/v?%version=%' >> $GITHUB_OUTPUT
          echo "${GITHUB_REF}" | sed -E 's%^refs/tags/%tag=%' >> $GITHUB_OUTPUT

      - name: Parse Version
        uses: madhead/semver-utils@v4
        id: parse_version
        with:
          version: ${{ steps.get_version.outputs.version }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        id: php
        with:
          php-version: pre-installed
          extensions: json
          tools: composer
        env:
          fail-fast: true

      - name: Install Dependencies
        id: deps
        run: composer install --no-dev --no-scripts --quiet --no-ansi --no-interaction --no-suggest --no-progress

      - name: Build Project
        id: build
        run: |
          git archive -o /tmp/${{ github.event.repository.name }}-${{ steps.get_version.outputs.version }}.zip --prefix=${{ github.event.repository.name }}/ ${{ steps.get_version.outputs.tag }}
          mkdir /tmp/${{ github.event.repository.name }}
          cp -R vendor /tmp/${{ github.event.repository.name }}/
          cd /tmp
          zip -r ${{ github.event.repository.name }}-${{ steps.get_version.outputs.version }}.zip ${{ github.event.repository.name }}/vendor

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/${{ github.event.repository.name }}-${{ steps.get_version.outputs.version }}.zip
          draft: true
          prerelease: ${{ steps.parse_version.outputs.prerelease != '' }}
